package io.github.rcrida.jcsp.solver.examples;

import io.github.rcrida.jcsp.ConstraintSatisfactionProblem;
import io.github.rcrida.jcsp.assignments.Assignment;
import io.github.rcrida.jcsp.domains.Domain;
import io.github.rcrida.jcsp.domains.IntRangeDomain;
import io.github.rcrida.jcsp.solver.Solver;
import io.github.rcrida.jcsp.variables.Variable;
import lombok.val;
import org.junit.jupiter.api.Test;

import java.util.HashSet;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Windoku (also called Hyper Sudoku or NRC Sudoku): a standard 9x9 Sudoku (row/column/box
 * all-different) plus four additional 3x3 "window" regions that must also contain 1-9 with no
 * repeats. The windows sit at rows/columns 2-4 and 6-8 (1-indexed) — offset by one from, and
 * overlapping, the standard box grid — and don't touch each other or the grid edges. This is the
 * standard Windoku region layout (confirmed against multiple published descriptions of the
 * variant); unlike {@code Prob057KillerSudokuTest}, Windoku has no CSPLib entry and no single
 * canonical example puzzle to transcribe, so this instance is constructed and verified directly:
 * the solution grid was generated by a standalone randomized backtracking filler (not this
 * library) satisfying all four constraint kinds simultaneously, then a set of 42 givens was chosen
 * and confirmed — via this library's own solver — to yield that exact grid as the sole solution.
 */
public class WindokuTest {
    static final Domain<Integer> DOMAIN = IntRangeDomain.of(1, 9);
    static Variable<Integer>[][] VARIABLES;

    /** The four window regions' top-left corners (0-indexed): rows/columns 2-4 and 6-8, 1-indexed. */
    static final int[] WINDOW_STARTS = {1, 5};

    /** The unique solution to {@link #PUZZLE} below, used only to verify our own result. */
    static final int[][] SOLUTION = {
            {9,6,5,7,1,2,8,3,4},
            {3,7,4,6,8,9,2,1,5},
            {2,1,8,3,4,5,6,7,9},
            {1,9,2,5,7,4,3,8,6},
            {7,4,3,8,6,1,9,5,2},
            {8,5,6,9,2,3,7,4,1},
            {4,8,7,2,5,6,1,9,3},
            {6,3,1,4,9,8,5,2,7},
            {5,2,9,1,3,7,4,6,8},
    };

    /** Givens (0 = blank); 42 clues, confirmed to force {@link #SOLUTION} uniquely. */
    static final int[][] PUZZLE = {
            {9,0,5,0,1,0,8,0,4},
            {0,7,0,6,0,9,0,1,0},
            {2,0,8,0,4,0,6,0,9},
            {1,9,0,5,0,4,0,8,0},
            {7,0,3,0,6,0,9,0,2},
            {0,5,0,9,0,3,0,4,0},
            {4,0,7,0,5,0,1,0,3},
            {0,3,0,4,0,8,0,2,0},
            {5,0,9,0,3,0,4,0,8},
    };

    @SuppressWarnings("unchecked")
    public static ConstraintSatisfactionProblem windoku() {
        val builder = ConstraintSatisfactionProblem.builder();
        VARIABLES = new Variable[9][9];
        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                VARIABLES[r][c] = Variable.Factory.INSTANCE.create("r" + r + "c" + c);
                builder.variableDomain(VARIABLES[r][c], DOMAIN);
            }
        }
        for (int r = 0; r < 9; r++) {
            val row = new HashSet<Variable<Integer>>();
            for (int c = 0; c < 9; c++) row.add(VARIABLES[r][c]);
            builder.allDiffConstraint(row);
        }
        for (int c = 0; c < 9; c++) {
            val column = new HashSet<Variable<Integer>>();
            for (int r = 0; r < 9; r++) column.add(VARIABLES[r][c]);
            builder.allDiffConstraint(column);
        }
        for (int br = 0; br < 9; br += 3) {
            for (int bc = 0; bc < 9; bc += 3) {
                val box = new HashSet<Variable<Integer>>();
                for (int r = 0; r < 3; r++) for (int c = 0; c < 3; c++) box.add(VARIABLES[br + r][bc + c]);
                builder.allDiffConstraint(box);
            }
        }
        for (int wr : WINDOW_STARTS) {
            for (int wc : WINDOW_STARTS) {
                val window = new HashSet<Variable<Integer>>();
                for (int r = 0; r < 3; r++) for (int c = 0; c < 3; c++) window.add(VARIABLES[wr + r][wc + c]);
                builder.allDiffConstraint(window);
            }
        }
        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                if (PUZZLE[r][c] != 0) builder.equalsConstraint(VARIABLES[r][c], PUZZLE[r][c]);
            }
        }
        return builder.build();
    }

    @Test
    void solvesToTheKnownUniqueSolution() {
        val csp = windoku();
        val solver = Solver.Factory.INSTANCE.createSolver(csp);
        val solution = solver.getSolution();
        assertThat(solution).isPresent();
        Assignment assignment = solution.get();
        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                assertThat(assignment.getValue(VARIABLES[r][c])).hasValue(SOLUTION[r][c]);
            }
        }
    }

    @Test
    void solutionIsUnique() {
        val csp = windoku();
        val solver = Solver.Factory.INSTANCE.createSolver(csp);
        assertThat(solver.getSolutions()).hasSize(1);
    }
}
