package org.jcsp.solver;

import lombok.Value;
import lombok.extern.slf4j.Slf4j;
import lombok.val;
import org.jcsp.ConstraintSatisfactionProblem;
import org.jcsp.assignments.Assignment;
import org.jcsp.constraints.Constraint;
import org.jcsp.constraints.unary.UnaryConstraint;
import org.jcsp.solver.assignmentfactory.InitialAssignmentFactory;
import org.jcsp.variables.Variable;
import org.jspecify.annotations.NonNull;

import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ThreadLocalRandom;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * The {@code MinConflictsSolver} class implements the local search technique for solving
 * constraint satisfaction problems (CSPs) using the Min-Conflicts heuristic. This approach is designed
 * to navigate the solution space by iteratively minimizing the number of conflicts in the current assignment.
 * <p>
 * Key Features:
 * - Utilizes an initial assignment generated by an {@link InitialAssignmentFactory} as a starting point.
 * - Iteratively attempts to resolve conflicts for a configurable number of maximum steps (`maxSteps`).
 * - Leverages a weighted strategy for constraints to improve search efficiency over time.
 * - Logs the state of the assignment and variable updates at each iteration for debugging purposes.
 * <p>
 * The algorithm works by:
 * 1. Selecting a variable currently involved in at least one violated constraint.
 * 2. Assigning the variable a value from its domain that minimizes the number of conflicts.
 * 3. Updating the weight of violated constraints to make them more likely to influence future iterations.
 * <p>
 * If a solution is found within the specified number of steps, the method will return the corresponding assignment.
 * Otherwise, it will return an empty {@link Optional}.
 * <p>
 * Parameters:
 * - {@code maxSteps}: The maximum number of steps the solver will take to attempt finding a solution.
 */
@Slf4j
@Value
public class MinConflictsSolver implements LocalSolver {
    int maxSteps;

    @Override
    public Optional<Assignment> getLocalSolution(@NonNull ConstraintSatisfactionProblem csp, @NonNull InitialAssignmentFactory factory) {
        var current = factory.getAssignment(csp);
        val constraintWeights = new HashMap<Constraint, Double>();
        for (int i = 0; i < maxSteps; i++) {
            log.info("Current assignment: {} -> {}", i, current);
            if (current.isSolution(csp)) {
                return Optional.of(current);
            }
            val variable = selectConflictedVariable(csp, current);
            val value = minimizeConflicts(csp, variable, current, constraintWeights);
            log.info("{} -> {}", variable, value);
            current = current.toBuilder().value(variable, value).build();
            updateWeights(csp, constraintWeights, current);
        }
        return Optional.empty();
    }

    /**
     * Selects a conflicted variable from the current assignment in the context of the given
     * constraint satisfaction problem. A variable is considered conflicted if it violates
     * one or more constraints in the current assignment.
     *
     * @param csp The constraint satisfaction problem containing the set of variables and constraints.
     * @param current The current assignment of variable values, used to determine which variables
     *                are in conflict.
     * @return A variable that is in conflict based on the current assignment. If multiple
     *         variables are in conflict, a randomly selected one is returned.
     */
    // Binary constraints expanded from n-ary constraints give better conflict granularity than
    // treating an n-ary constraint as a single violation. Unary constraints are added separately
    // as they have no binary representation.
    private Stream<Constraint> conflictConstraints(@NonNull ConstraintSatisfactionProblem csp) {
        return Stream.concat(
                csp.getAllBinaryConstraints().stream(),
                csp.getConstraints().stream().filter(c -> c instanceof UnaryConstraint));
    }

    private @NonNull Variable selectConflictedVariable(@NonNull ConstraintSatisfactionProblem csp, @NonNull Assignment current) {
        val conflictedVariables = csp.getConstraints().stream()
                .filter(Predicate.not(constraint -> constraint.isSatisfiedBy(current)))
                .flatMap(constraint -> constraint.getVariables().stream())
                .distinct()
                .toList();
        return conflictedVariables.get(ThreadLocalRandom.current().nextInt(conflictedVariables.size()));
    }

    /**
     * Selects the value for the specified variable that minimizes the total weight of violated constraints in
     * the context of the given constraint satisfaction problem.
     * This method evaluates every possible value in the domain of the variable and computes conflict weights.
     * It then selects the value with the least conflict weight to reduce constraint violations.
     *
     * @param csp The constraint satisfaction problem containing variables, domains, and constraints.
     * @param variable The variable for which a value will be selected to minimize conflicts.
     * @param current The current assignment of variables, against which constraints will be evaluated.
     * @param constraintWeights A map assigning weights to constraints, representing their relative importance.
     * @return The value from the variable's domain that minimizes the total weight of violated constraints.
     */
    private @NonNull Object minimizeConflicts(@NonNull ConstraintSatisfactionProblem csp, @NonNull Variable variable, @NonNull Assignment current, @NonNull Map<Constraint, Double> constraintWeights) {
        val variableConstraints = conflictConstraints(csp)
                .filter(constraint -> constraint.getVariables().contains(variable))
                .toList();
        val domain = csp.getVariableDomains().get(variable);
        val valueWeights = domain.stream()
                .collect(Collectors.toMap(v -> v, v -> weighConflicts(variable, v, current, variableConstraints, constraintWeights)));
        log.debug("Value weights: {}", valueWeights);
        val minWeight = valueWeights.values().stream().min(Comparator.naturalOrder()).orElseThrow();
        val leastConflictedValues = valueWeights.entrySet().stream()
                .filter(e -> e.getValue().equals(minWeight))
                .map(Map.Entry::getKey)
                .toList();
        return leastConflictedValues.get(ThreadLocalRandom.current().nextInt(leastConflictedValues.size()));
    }

    /**
     * Computes the total weight of unsatisfied constraints when a variable is assigned a specific value.
     * This method evaluates all constraints associated with the variable and accumulates the weights
     * of those that are violated under the given assignment.
     *
     * @param variable The variable for which the value is being evaluated.
     * @param value The value being assigned to the variable.
     * @param current The current assignment of variables, used to create a candidate assignment
     *                with the new value for the variable.
     * @param variableConstraints A list of constraints specifically associated with the variable
     *                            whose assignment is being analyzed.
     * @param constraintWeights A map containing the weights of each constraint, where a higher
     *                          weight indicates more importance. Default weight is 1.0 if a constraint
     *                          is not explicitly present in the map.
     * @return The total weight of constraints that are violated when the variable is assigned the given value.
     */
    private double weighConflicts(@NonNull Variable variable, @NonNull Object value, @NonNull Assignment current, @NonNull List<? extends Constraint> variableConstraints, @NonNull Map<Constraint, Double> constraintWeights) {
        val candidate = current.withValue(variable, value);
        return variableConstraints.stream()
                .filter(Predicate.not(constraint -> constraint.isSatisfiedBy(candidate)))
                .map(constraint -> constraintWeights.getOrDefault(constraint, 1.0))
                .reduce(0.0, Double::sum);
    }

    /**
     * Updates the weights associated with constraints in a constraint satisfaction problem (CSP),
     * penalizing constraints that are violated in the given assignment.
     *
     * @param csp The constraint satisfaction problem containing the set of constraints.
     * @param constraintWeights A map of constraints to their respective weights. This map will
     *                          be updated by incrementing the weight of any violated constraint
     *                          by 1.
     * @param current The current variable assignment being evaluated. This assignment is used to
     *                check which constraints are not satisfied.
     */
    private void updateWeights(@NonNull ConstraintSatisfactionProblem csp, @NonNull Map<Constraint, Double> constraintWeights, @NonNull Assignment current) {
        conflictConstraints(csp)
                .filter(Predicate.not(constraint -> constraint.isSatisfiedBy(current)))
                .forEach(constraint -> {
                    val currentWeight = constraintWeights.getOrDefault(constraint, 1.0);
                    constraintWeights.put(constraint, currentWeight + 1);
                });
        log.debug("Constraint weights {}", constraintWeights);
    }
}
