package io.github.rcrida.jcsp.solver;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.AccessLevel;
import lombok.ToString;
import lombok.Value;
import lombok.extern.slf4j.Slf4j;
import lombok.val;
import io.github.rcrida.jcsp.ConstraintSatisfactionProblem;
import io.github.rcrida.jcsp.assignments.Assignment;
import io.github.rcrida.jcsp.constraints.Constraint;
import io.github.rcrida.jcsp.domains.DiscreteDomain;
import io.github.rcrida.jcsp.solver.assignmentfactory.InitialAssignmentFactory;
import io.github.rcrida.jcsp.solver.backtrackingsearch.selector.ConflictedVariableSelector;
import io.github.rcrida.jcsp.solver.backtrackingsearch.selector.UnassignedVariableSelector;
import io.github.rcrida.jcsp.variables.Variable;
import org.jspecify.annotations.NonNull;

import java.util.Comparator;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ThreadLocalRandom;
import java.util.function.ToDoubleFunction;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

/**
 * The {@code MinConflictsSolver} class implements the local search technique for solving
 * constraint satisfaction problems (CSPs) using the Min-Conflicts heuristic. This approach is designed
 * to navigate the solution space by iteratively minimizing the number of conflicts in the current assignment.
 * <p>
 * Key Features:
 * - Utilizes an initial assignment generated by an {@link InitialAssignmentFactory} as a starting point.
 * - Iteratively attempts to resolve conflicts for a configurable number of maximum steps (`maxSteps`).
 * - Leverages a weighted strategy for constraints to improve search efficiency over time.
 * - Logs the state of the assignment and variable updates at each iteration for debugging purposes.
 * <p>
 * The algorithm works by:
 * 1. Selecting a variable currently involved in at least one violated constraint.
 * 2. Assigning the variable a value from its domain that minimizes the number of conflicts.
 * 3. Updating the weight of violated constraints to make them more likely to influence future iterations.
 * <p>
 * If a solution is found within the specified number of steps, the method will return the corresponding assignment.
 * Otherwise, it will return an empty {@link Optional}.
 * <p>
 * Parameters:
 * - {@code maxSteps}: The maximum number of steps the solver will take to attempt finding a solution.
 */
@Slf4j
@Value
@Builder(toBuilder = true)
public class MinConflictsSolver implements LocalSolver, CancellableLocalSolver {
    int maxAttempts;
    int maxSteps;
    @NonNull InitialAssignmentFactory initialAssignmentFactory;
    @Builder.Default UnassignedVariableSelector conflictedVariableSelector = ConflictedVariableSelector.INSTANCE;

    /**
     * Cooperative cancellation, only ever set by {@link RaceLocalSolver} via {@link #withCancellation}.
     * Excluded from equals/hashCode/toString since it's ephemeral race state, not configuration —
     * same reasoning as {@link io.github.rcrida.jcsp.assignments.SolverLimits}'s limitHitStats field.
     */
    @Builder.Default
    @EqualsAndHashCode.Exclude
    @ToString.Exclude
    @Getter(AccessLevel.NONE)
    Cancellation cancellation = Cancellation.NEVER;

    public static MinConflictsSolver of(int maxAttempts, int maxSteps, @NonNull InitialAssignmentFactory factory) {
        return builder().maxAttempts(maxAttempts).maxSteps(maxSteps).initialAssignmentFactory(factory).build();
    }

    @Override
    public MinConflictsSolver withCancellation(@NonNull Cancellation cancellation) {
        return toBuilder().cancellation(cancellation).build();
    }

    @Override
    public Optional<Assignment> getLocalSolution(@NonNull ConstraintSatisfactionProblem csp) {
        return IntStream.range(0, maxAttempts)
                .parallel()
                .unordered()
                .mapToObj(attempt -> solveAttempt(csp, attempt))
                .filter(Optional::isPresent)
                .findFirst()
                .orElse(Optional.empty());
    }

    private Optional<Assignment> solveAttempt(@NonNull ConstraintSatisfactionProblem csp, int attempt) {
        var current = initialAssignmentFactory.getAssignment(csp);
        val constraintWeights = new HashMap<Constraint, Double>();
        for (int step = 0; step < maxSteps && !cancellation.isCancelled(); step++) {
            if (current.isSolution(csp)) {
                log.info("Solution at attempt {} step {}", attempt, step);
                return Optional.of(current);
            }
            val variable = conflictedVariableSelector.select(csp, current);
            current = applyMinConflicts(csp, variable, current, constraintWeights);
            current.getStatistics().incrementSteps();
            updateWeights(csp, constraintWeights, current);
        }
        return Optional.empty();
    }

    @Override
    public Optional<Assignment> getLocalSolution(@NonNull ConstraintSatisfactionProblem csp,
                                                 @NonNull ToDoubleFunction<Assignment> objective) {
        return IntStream.range(0, maxAttempts)
                .parallel()
                .mapToObj(attempt -> solveAttemptWithObjective(csp, attempt, objective))
                .filter(Optional::isPresent)
                .map(Optional::get)
                .min(Comparator.comparingDouble(objective));
    }

    private Optional<Assignment> solveAttemptWithObjective(@NonNull ConstraintSatisfactionProblem csp, int attempt,
                                                            @NonNull ToDoubleFunction<Assignment> objective) {
        var current = initialAssignmentFactory.getAssignment(csp);
        val constraintWeights = new HashMap<Constraint, Double>();
        for (int step = 0; step < maxSteps && !cancellation.isCancelled(); step++) {
            if (current.isSolution(csp)) {
                double cost = objective.applyAsDouble(current);
                log.info("Found solution at attempt {} step {} with cost {}", attempt, step, cost);
                return Optional.of(current);
            }
            val variable = conflictedVariableSelector.select(csp, current);
            current = applyMinConflictsAndObjective(csp, variable, current, constraintWeights, objective);
            current.getStatistics().incrementSteps();
            updateWeights(csp, constraintWeights, current);
        }
        return Optional.empty();
    }

    private @NonNull Assignment applyMinConflictsAndObjective(@NonNull ConstraintSatisfactionProblem csp,
                                                               @NonNull Variable<?> variable,
                                                               @NonNull Assignment current,
                                                               @NonNull Map<Constraint, Double> constraintWeights,
                                                               @NonNull ToDoubleFunction<Assignment> objective) {
        return applyMinConflictsAndObjectiveTyped(csp, variable, current, constraintWeights, objective);
    }

    private <T> @NonNull Assignment applyMinConflictsAndObjectiveTyped(@NonNull ConstraintSatisfactionProblem csp,
                                                                        @NonNull Variable<T> variable,
                                                                        @NonNull Assignment current,
                                                                        @NonNull Map<Constraint, Double> constraintWeights,
                                                                        @NonNull ToDoubleFunction<Assignment> objective) {
        record ValueCost<V>(V value, double violations, double objective) {}

        val variableConstraints = LocalSearchSupport.conflictConstraints(csp)
                .filter(c -> c.getVariables().contains(variable))
                .toList();
        val costs = ((DiscreteDomain<T>) csp.getDomain(variable)).stream()
                .map(v -> new ValueCost<>(v,
                        LocalSearchSupport.weighConflicts(variable, v, current, variableConstraints, constraintWeights),
                        objective.applyAsDouble(current.withValue(variable, v))))
                .toList();

        // Lexicographic: minimise violations first (constraint repair always takes priority),
        // then use the objective as a tie-breaker — no scaling constant needed.
        double minViolations = costs.stream().mapToDouble(ValueCost::violations).min().orElseThrow();
        double minObjective  = costs.stream().filter(c -> c.violations() == minViolations)
                .mapToDouble(ValueCost::objective).min().orElseThrow();
        val candidates = costs.stream()
                .filter(c -> c.violations() == minViolations && c.objective() == minObjective)
                .map(ValueCost::value)
                .toList();
        T value = candidates.get(ThreadLocalRandom.current().nextInt(candidates.size()));
        log.debug("{} -> {}", variable, value);
        return current.toBuilder().value(variable, value).build();
    }

    /**
     * Selects the value for the specified variable that minimizes the total weight of violated constraints in
     * the context of the given constraint satisfaction problem.
     * This method evaluates every possible value in the domain of the variable and computes conflict weights.
     * It then selects the value with the least conflict weight to reduce constraint violations.
     *
     * @param csp The constraint satisfaction problem containing variables, domains, and constraints.
     * @param variable The variable for which a value will be selected to minimize conflicts.
     * @param current The current assignment of variables, against which constraints will be evaluated.
     * @param constraintWeights A map assigning weights to constraints, representing their relative importance.
     * @return The value from the variable's domain that minimizes the total weight of violated constraints.
     */
    private @NonNull Assignment applyMinConflicts(@NonNull ConstraintSatisfactionProblem csp,
                                                   @NonNull Variable<?> variable,
                                                   @NonNull Assignment current,
                                                   @NonNull Map<Constraint, Double> constraintWeights) {
        return applyMinConflictsTyped(csp, variable, current, constraintWeights);
    }

    private <T> @NonNull Assignment applyMinConflictsTyped(@NonNull ConstraintSatisfactionProblem csp,
                                                            @NonNull Variable<T> variable,
                                                            @NonNull Assignment current,
                                                            @NonNull Map<Constraint, Double> constraintWeights) {
        val variableConstraints = LocalSearchSupport.conflictConstraints(csp)
                .filter(constraint -> constraint.getVariables().contains(variable))
                .toList();
        Map<T, Double> valueWeights = ((DiscreteDomain<T>) csp.getDomain(variable)).stream()
                .collect(Collectors.toMap(v -> v, v -> LocalSearchSupport.weighConflicts(variable, v, current, variableConstraints, constraintWeights)));
        log.debug("Value weights: {}", valueWeights);
        val minWeight = valueWeights.values().stream().min(Comparator.naturalOrder()).orElseThrow();
        val candidates = valueWeights.entrySet().stream()
                .filter(e -> e.getValue().equals(minWeight))
                .map(Map.Entry::getKey)
                .toList();
        T value = candidates.get(ThreadLocalRandom.current().nextInt(candidates.size()));
        log.info("{} -> {}", variable, value);
        return current.toBuilder().value(variable, value).build();
    }

    /**
     * Updates the weights associated with constraints in a constraint satisfaction problem (CSP),
     * penalizing constraints that are violated in the given assignment.
     *
     * @param csp The constraint satisfaction problem containing the set of constraints.
     * @param constraintWeights A map of constraints to their respective weights. This map will
     *                          be updated by incrementing the weight of any violated constraint
     *                          by 1.
     * @param current The current variable assignment being evaluated. This assignment is used to
     *                check which constraints are not satisfied.
     */
    private void updateWeights(@NonNull ConstraintSatisfactionProblem csp, @NonNull Map<Constraint, Double> constraintWeights, @NonNull Assignment current) {
        LocalSearchSupport.incrementViolatedWeights(csp, constraintWeights, current);
        log.debug("Constraint weights {}", constraintWeights);
    }
}
