package io.github.rcrida.jcsp.solver;

import lombok.Builder;
import lombok.Value;
import lombok.extern.slf4j.Slf4j;
import lombok.val;
import io.github.rcrida.jcsp.ConstraintSatisfactionProblem;
import io.github.rcrida.jcsp.assignments.Assignment;
import io.github.rcrida.jcsp.constraints.Constraint;
import io.github.rcrida.jcsp.constraints.unary.UnaryConstraint;
import io.github.rcrida.jcsp.solver.assignmentfactory.InitialAssignmentFactory;
import io.github.rcrida.jcsp.solver.backtrackingsearch.selector.ConflictedVariableSelector;
import io.github.rcrida.jcsp.solver.backtrackingsearch.selector.UnassignedVariableSelector;
import io.github.rcrida.jcsp.variables.Variable;
import org.jspecify.annotations.NonNull;

import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ThreadLocalRandom;
import java.util.function.Predicate;
import java.util.function.ToDoubleFunction;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * The {@code MinConflictsSolver} class implements the local search technique for solving
 * constraint satisfaction problems (CSPs) using the Min-Conflicts heuristic. This approach is designed
 * to navigate the solution space by iteratively minimizing the number of conflicts in the current assignment.
 * <p>
 * Key Features:
 * - Utilizes an initial assignment generated by an {@link InitialAssignmentFactory} as a starting point.
 * - Iteratively attempts to resolve conflicts for a configurable number of maximum steps (`maxSteps`).
 * - Leverages a weighted strategy for constraints to improve search efficiency over time.
 * - Logs the state of the assignment and variable updates at each iteration for debugging purposes.
 * <p>
 * The algorithm works by:
 * 1. Selecting a variable currently involved in at least one violated constraint.
 * 2. Assigning the variable a value from its domain that minimizes the number of conflicts.
 * 3. Updating the weight of violated constraints to make them more likely to influence future iterations.
 * <p>
 * If a solution is found within the specified number of steps, the method will return the corresponding assignment.
 * Otherwise, it will return an empty {@link Optional}.
 * <p>
 * Parameters:
 * - {@code maxSteps}: The maximum number of steps the solver will take to attempt finding a solution.
 */
@Slf4j
@Value
@Builder
public class MinConflictsSolver implements LocalSolver {
    int maxSteps;
    @NonNull InitialAssignmentFactory initialAssignmentFactory;
    @Builder.Default UnassignedVariableSelector conflictedVariableSelector = ConflictedVariableSelector.INSTANCE;

    /** Convenience factory method for the common case of maxSteps only. */
    public static MinConflictsSolver of(int maxSteps, @NonNull InitialAssignmentFactory factory) {
        return builder().maxSteps(maxSteps).initialAssignmentFactory(factory).build();
    }

    @Override
    public Optional<Assignment> getLocalSolution(@NonNull ConstraintSatisfactionProblem csp) {
        var current = initialAssignmentFactory.getAssignment(csp);
        val constraintWeights = new HashMap<Constraint, Double>();
        for (int i = 0; i < maxSteps; i++) {
            if (current.isSolution(csp)) {
                return Optional.of(current);
            }
            val variable = conflictedVariableSelector.select(csp, current);
            current = applyMinConflicts(csp, variable, current, constraintWeights);
            updateWeights(csp, constraintWeights, current);
        }
        return Optional.empty();
    }

    @Override
    public Optional<Assignment> getLocalSolution(@NonNull ConstraintSatisfactionProblem csp,
                                                 @NonNull ToDoubleFunction<Assignment> objective) {
        val constraintWeights = new HashMap<Constraint, Double>();
        Optional<Assignment> best = Optional.empty();
        double bestCost = Double.MAX_VALUE;
        var current = initialAssignmentFactory.getAssignment(csp);
        for (int i = 0; i < maxSteps; i++) {
            if (current.isSolution(csp)) {
                double cost = objective.applyAsDouble(current);
                if (cost < bestCost) {
                    bestCost = cost;
                    best = Optional.of(current);
                    log.info("Improving solution at step {} with cost {}: {}", i, cost, current);
                }
                // Restart from a new initial assignment — perturbing a feasible local optimum
                // always reassigns the selected variable to its current value, making no progress.
                constraintWeights.clear();
                current = initialAssignmentFactory.getAssignment(csp);
                continue;
            }
            val variable = conflictedVariableSelector.select(csp, current);
            current = applyMinConflictsAndObjective(csp, variable, current, constraintWeights, objective);
            updateWeights(csp, constraintWeights, current);
        }
        return best;
    }

    private @NonNull Assignment applyMinConflictsAndObjective(@NonNull ConstraintSatisfactionProblem csp,
                                                               @NonNull Variable<?> variable,
                                                               @NonNull Assignment current,
                                                               @NonNull Map<Constraint, Double> constraintWeights,
                                                               @NonNull ToDoubleFunction<Assignment> objective) {
        return applyMinConflictsAndObjectiveTyped(csp, variable, current, constraintWeights, objective);
    }

    private <T> @NonNull Assignment applyMinConflictsAndObjectiveTyped(@NonNull ConstraintSatisfactionProblem csp,
                                                                        @NonNull Variable<T> variable,
                                                                        @NonNull Assignment current,
                                                                        @NonNull Map<Constraint, Double> constraintWeights,
                                                                        @NonNull ToDoubleFunction<Assignment> objective) {
        record ValueCost<V>(V value, double violations, double objective) {}

        val variableConstraints = conflictConstraints(csp)
                .filter(c -> c.getVariables().contains(variable))
                .toList();
        val costs = csp.getDomain(variable).stream()
                .map(v -> new ValueCost<>(v,
                        weighConflicts(variable, v, current, variableConstraints, constraintWeights),
                        objective.applyAsDouble(current.withValue(variable, v))))
                .toList();

        // Lexicographic: minimise violations first (constraint repair always takes priority),
        // then use the objective as a tie-breaker — no scaling constant needed.
        double minViolations = costs.stream().mapToDouble(ValueCost::violations).min().orElseThrow();
        double minObjective  = costs.stream().filter(c -> c.violations() == minViolations)
                .mapToDouble(ValueCost::objective).min().orElseThrow();
        val candidates = costs.stream()
                .filter(c -> c.violations() == minViolations && c.objective() == minObjective)
                .map(ValueCost::value)
                .toList();
        T value = candidates.get(ThreadLocalRandom.current().nextInt(candidates.size()));
        log.debug("{} -> {}", variable, value);
        return current.toBuilder().value(variable, value).build();
    }

    /**
     * Selects a conflicted variable from the current assignment in the context of the given
     * constraint satisfaction problem. A variable is considered conflicted if it violates
     * one or more constraints in the current assignment.
     *
     * @param csp The constraint satisfaction problem containing the set of variables and constraints.
     * @return A variable that is in conflict based on the current assignment. If multiple
     *         variables are in conflict, a randomly selected one is returned.
     */
    // Binary constraints expanded from n-ary constraints give better conflict granularity than
    // treating an n-ary constraint as a single violation. Unary constraints are added separately
    // as they have no binary representation.
    private Stream<Constraint> conflictConstraints(@NonNull ConstraintSatisfactionProblem csp) {
        return Stream.concat(
                csp.getAllBinaryConstraints().stream(),
                csp.getConstraints().stream().filter(c -> c instanceof UnaryConstraint));
    }

    /**
     * Selects the value for the specified variable that minimizes the total weight of violated constraints in
     * the context of the given constraint satisfaction problem.
     * This method evaluates every possible value in the domain of the variable and computes conflict weights.
     * It then selects the value with the least conflict weight to reduce constraint violations.
     *
     * @param csp The constraint satisfaction problem containing variables, domains, and constraints.
     * @param variable The variable for which a value will be selected to minimize conflicts.
     * @param current The current assignment of variables, against which constraints will be evaluated.
     * @param constraintWeights A map assigning weights to constraints, representing their relative importance.
     * @return The value from the variable's domain that minimizes the total weight of violated constraints.
     */
    private @NonNull Assignment applyMinConflicts(@NonNull ConstraintSatisfactionProblem csp,
                                                   @NonNull Variable<?> variable,
                                                   @NonNull Assignment current,
                                                   @NonNull Map<Constraint, Double> constraintWeights) {
        return applyMinConflictsTyped(csp, variable, current, constraintWeights);
    }

    private <T> @NonNull Assignment applyMinConflictsTyped(@NonNull ConstraintSatisfactionProblem csp,
                                                            @NonNull Variable<T> variable,
                                                            @NonNull Assignment current,
                                                            @NonNull Map<Constraint, Double> constraintWeights) {
        val variableConstraints = conflictConstraints(csp)
                .filter(constraint -> constraint.getVariables().contains(variable))
                .toList();
        Map<T, Double> valueWeights = csp.getDomain(variable).stream()
                .collect(Collectors.toMap(v -> v, v -> weighConflicts(variable, v, current, variableConstraints, constraintWeights)));
        log.debug("Value weights: {}", valueWeights);
        val minWeight = valueWeights.values().stream().min(Comparator.naturalOrder()).orElseThrow();
        val candidates = valueWeights.entrySet().stream()
                .filter(e -> e.getValue().equals(minWeight))
                .map(Map.Entry::getKey)
                .toList();
        T value = candidates.get(ThreadLocalRandom.current().nextInt(candidates.size()));
        log.info("{} -> {}", variable, value);
        return current.toBuilder().value(variable, value).build();
    }

    /**
     * Computes the total weight of unsatisfied constraints when a variable is assigned a specific value.
     * This method evaluates all constraints associated with the variable and accumulates the weights
     * of those that are violated under the given assignment.
     *
     * @param variable The variable for which the value is being evaluated.
     * @param value The value being assigned to the variable.
     * @param current The current assignment of variables, used to create a candidate assignment
     *                with the new value for the variable.
     * @param variableConstraints A list of constraints specifically associated with the variable
     *                            whose assignment is being analyzed.
     * @param constraintWeights A map containing the weights of each constraint, where a higher
     *                          weight indicates more importance. Default weight is 1.0 if a constraint
     *                          is not explicitly present in the map.
     * @return The total weight of constraints that are violated when the variable is assigned the given value.
     */
    private <T> double weighConflicts(@NonNull Variable<T> variable, @NonNull T value, @NonNull Assignment current, @NonNull List<? extends Constraint> variableConstraints, @NonNull Map<Constraint, Double> constraintWeights) {
        val candidate = current.withValue(variable, value);
        return variableConstraints.stream()
                .filter(Predicate.not(constraint -> constraint.isSatisfiedBy(candidate)))
                .map(constraint -> constraintWeights.getOrDefault(constraint, 1.0))
                .reduce(0.0, Double::sum);
    }

    /**
     * Updates the weights associated with constraints in a constraint satisfaction problem (CSP),
     * penalizing constraints that are violated in the given assignment.
     *
     * @param csp The constraint satisfaction problem containing the set of constraints.
     * @param constraintWeights A map of constraints to their respective weights. This map will
     *                          be updated by incrementing the weight of any violated constraint
     *                          by 1.
     * @param current The current variable assignment being evaluated. This assignment is used to
     *                check which constraints are not satisfied.
     */
    private void updateWeights(@NonNull ConstraintSatisfactionProblem csp, @NonNull Map<Constraint, Double> constraintWeights, @NonNull Assignment current) {
        conflictConstraints(csp)
                .filter(Predicate.not(constraint -> constraint.isSatisfiedBy(current)))
                .forEach(constraint -> {
                    val currentWeight = constraintWeights.getOrDefault(constraint, 1.0);
                    constraintWeights.put(constraint, currentWeight + 1);
                });
        log.debug("Constraint weights {}", constraintWeights);
    }
}
